/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import javax.swing.JOptionPane;
import Controlador.ControlProducto;
import Modelo.Categoria;
import Modelo.Producto;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
//import Modelo.Conexion;   //prueba para comprobar conexion correcta el inicio
/**
 *
 * @author hanna
 */
public class VistaProducto extends javax.swing.JFrame {

    /**
     * Creates new form vistaProducto
     */
    public VistaProducto() {
        initComponents();
        this.listar();// ejecuto en la vista el metodo listar creado abajo
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cboxCategoria = new javax.swing.JComboBox<>();
        buttonRegistrar = new javax.swing.JButton();
        txtCantidad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtNombreConsulta = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        buttonEliminar = new javax.swing.JButton();
        buttonActualizar = new javax.swing.JButton();
        buttonConsultar = new javax.swing.JButton();
        txtCantidadActualizar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPrecioActualizar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtNombreActualizar = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        labelIDActualizar = new javax.swing.JLabel();
        buttonRefrescar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GESTION DE PRODUCTOS");
        setBackground(new java.awt.Color(0, 204, 255));

        jTabbedPane3.setBackground(java.awt.SystemColor.controlHighlight);
        jTabbedPane3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 153, 255), new java.awt.Color(102, 153, 255), null, new java.awt.Color(0, 153, 255)));
        jTabbedPane3.setForeground(new java.awt.Color(0, 51, 153));
        jTabbedPane3.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        jTabbedPane3.setOpaque(true);

        jPanel4.setBackground(java.awt.SystemColor.activeCaption);
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setToolTipText("");
        jPanel4.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Lucida Console", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTRO DE PRODUCTO");

        txtNombre.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("NOMBRE:");

        cboxCategoria.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        cboxCategoria.setForeground(new java.awt.Color(0, 51, 153));
        cboxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Viveres", "Lacteos", "Carnicos", "Aseo", "Miscelaneos", "Bebidas", "Panaderia", "Papeleria", " ", " ", " " }));
        cboxCategoria.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cboxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxCategoriaActionPerformed(evt);
            }
        });

        buttonRegistrar.setBackground(java.awt.SystemColor.activeCaptionBorder);
        buttonRegistrar.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        buttonRegistrar.setForeground(new java.awt.Color(0, 51, 153));
        buttonRegistrar.setText("Registrar Producto");
        buttonRegistrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegistrarActionPerformed(evt);
            }
        });

        txtCantidad.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setText("CANTIDAD:");

        txtPrecio.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 102));
        jLabel5.setText("PRECIO:");

        jLabel6.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 102));
        jLabel6.setText("CATEGORIA:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5))
                                .addGap(7, 7, 7)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtPrecio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cboxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(buttonRegistrar)
                .addGap(41, 41, 41))
        );

        jTabbedPane3.addTab("REGISTRO", jPanel4);

        jPanel5.setBackground(java.awt.SystemColor.activeCaption);
        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Lucida Console", 1, 28)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 153));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("CONSULTA DE PRODUCTOS");

        txtNombreConsulta.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        txtNombreConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreConsultaActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 102));
        jLabel7.setText("NOMBRE:");

        buttonEliminar.setBackground(java.awt.SystemColor.activeCaptionBorder);
        buttonEliminar.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        buttonEliminar.setForeground(new java.awt.Color(0, 51, 153));
        buttonEliminar.setText("ELIMINAR");
        buttonEliminar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEliminarActionPerformed(evt);
            }
        });

        buttonActualizar.setBackground(java.awt.SystemColor.activeCaptionBorder);
        buttonActualizar.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        buttonActualizar.setForeground(new java.awt.Color(0, 51, 153));
        buttonActualizar.setText("ACTUALIZAR");
        buttonActualizar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActualizarActionPerformed(evt);
            }
        });

        buttonConsultar.setBackground(java.awt.SystemColor.activeCaptionBorder);
        buttonConsultar.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        buttonConsultar.setForeground(new java.awt.Color(0, 51, 153));
        buttonConsultar.setText("Consultar");
        buttonConsultar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConsultarActionPerformed(evt);
            }
        });

        txtCantidadActualizar.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        txtCantidadActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActualizarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 102));
        jLabel8.setText("CANTIDAD:");

        txtPrecioActualizar.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        txtPrecioActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActualizarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 102));
        jLabel9.setText("PRECIO:");

        txtNombreActualizar.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        txtNombreActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActualizarActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 102));
        jLabel10.setText("NOMBRE:");

        jTable1.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 51, 153));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel11.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 102));
        jLabel11.setText("ID:");

        labelIDActualizar.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        labelIDActualizar.setForeground(new java.awt.Color(0, 51, 102));
        labelIDActualizar.setText("0");

        buttonRefrescar.setBackground(java.awt.SystemColor.activeCaptionBorder);
        buttonRefrescar.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        buttonRefrescar.setForeground(new java.awt.Color(0, 51, 153));
        buttonRefrescar.setText("Refrescar");
        buttonRefrescar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonRefrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRefrescarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreConsulta)
                .addGap(18, 18, 18)
                .addComponent(buttonConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelIDActualizar))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(buttonRefrescar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(213, 213, 213))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(buttonActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addComponent(buttonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(txtNombreActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCantidadActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrecioActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(buttonConsultar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonRefrescar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNombreActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtCantidadActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtPrecioActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(labelIDActualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonActualizar)
                    .addComponent(buttonEliminar))
                .addContainerGap())
        );

        jTabbedPane3.addTab("CONSULTA", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void cboxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxCategoriaActionPerformed

    private void buttonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegistrarActionPerformed
        //Conexion objconecDataBase = new Conexion();// prueba para comprobar conexion correcta el inicio
        //objconecDataBase.conectar();//prueba para comprobar conexion correcta el inicio
        
        try{
            ControlProducto objControlP = new ControlProducto();
            Categoria objCategoria = new Categoria();
            
            String nombre = this.txtNombre.getText(); //Atrapo los textos en las cajas y los pongo en una variable
            String cantidad = this.txtCantidad.getText();
            int precio = Integer.parseInt(this.txtPrecio.getText()); // De la prueba que hicimos dejandolo como int en ControlProducto, aqui toca convertirlo a String

            if (this.cboxCategoria.getSelectedItem()=="Seleccione"){ //obtener lo que se esta seleccionando
                JOptionPane.showMessageDialog(this,"Seleccione una opcidon correcta ");
                }
            else if (this.cboxCategoria.getSelectedItem()== "Viveres"){
                objCategoria.setIdCategoria(1);
                objCategoria.setNombreCategoria("Viveres");
                }
            else if (this.cboxCategoria.getSelectedItem()== "Lacteos"){
                objCategoria.setIdCategoria(2);
                objCategoria.setNombreCategoria("Lacteos");
                }  
            else if (this.cboxCategoria.getSelectedItem()== "Carnicos"){
                objCategoria.setIdCategoria(3);
                objCategoria.setNombreCategoria("Carnicos");
                } 
            else if (this.cboxCategoria.getSelectedItem()== "Aseo"){
                objCategoria.setIdCategoria(4);
                objCategoria.setNombreCategoria("Aseo");
                } 
            else if (this.cboxCategoria.getSelectedItem()== "Miscelaneos"){
                objCategoria.setIdCategoria(5);
                objCategoria.setNombreCategoria("Miscelaneos");
                } 
            else if (this.cboxCategoria.getSelectedItem()== "Bebidas"){
                objCategoria.setIdCategoria(6);
                objCategoria.setNombreCategoria("Bebidas");
                } 
            else if (this.cboxCategoria.getSelectedItem()== "Panaderia"){
                objCategoria.setIdCategoria(7);
                objCategoria.setNombreCategoria("Panaderia");
                } 
            else if (this.cboxCategoria.getSelectedItem()== "Papeleria"){
                objCategoria.setIdCategoria(8);
                objCategoria.setNombreCategoria("Papeleria");
                } 
            
            objControlP.crear(nombre,cantidad,precio,objCategoria);
            JOptionPane.showMessageDialog(null,"Insertado correctamente");

            this.txtCantidad.setText(""); //Esto para limpiar las cajas de texto
            this.txtNombre.setText("");
            this.txtPrecio.setText("");
            this.cboxCategoria.setSelectedItem("Seleccione");
            }
        catch (Exception error){
            JOptionPane.showMessageDialog(null,"Error: " +error);
            }
        
    }//GEN-LAST:event_buttonRegistrarActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void txtNombreConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreConsultaActionPerformed

    private void buttonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEliminarActionPerformed
        // TODO add your handling code here:
        try{
            ControlProducto objctrPro = new ControlProducto();
            String id = this.labelIDActualizar.getText();
            
            //JOptionPane.showMessageDialog(null,"Eliminado correctamente");   que si esta seguro de eliminar         
            
            objctrPro.eliminar(id);
            JOptionPane.showMessageDialog(null,"Eliminado correctamente");
            
            this.txtCantidadActualizar.setText(""); //Esto para limpiar las cajas de texto
            this.txtNombreActualizar.setText("");
            this.txtPrecioActualizar.setText("");
            this.labelIDActualizar.setText("0");
            }
            catch (Exception error){
            JOptionPane.showMessageDialog(null,"Error: " +error);
            }
        
    }//GEN-LAST:event_buttonEliminarActionPerformed

    private void buttonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActualizarActionPerformed
        // TODO add your handling code here:
        try{
            ControlProducto objctrPro = new ControlProducto();
            String id = this.labelIDActualizar.getText();
            String nombre = this.txtNombreActualizar.getText();
            String cantidad = this.txtCantidadActualizar.getText();
            int precio = Integer.parseInt(this.txtPrecioActualizar.getText());
            
            objctrPro.actualizar(id, nombre, cantidad, precio);
            JOptionPane.showMessageDialog(null,"Actualizado correctamente");
            
            this.txtCantidadActualizar.setText(""); //Esto para limpiar las cajas de texto
            this.txtNombreActualizar.setText("");
            this.txtPrecioActualizar.setText("");
            this.labelIDActualizar.setText("0");
            }
            catch (Exception error){
            JOptionPane.showMessageDialog(null,"Error: " +error);
            }
        
    }//GEN-LAST:event_buttonActualizarActionPerformed

    private void buttonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConsultarActionPerformed
        // TODO add your handling code here:
        try{
            ControlProducto controlP = new ControlProducto(); //crea objeto de controlador
            DefaultTableModel tabla = new DefaultTableModel(); //crea un objeto tipo tabla
            ArrayList<Producto> consultaProducto = new ArrayList<>(); // crea un array de productos
            
            String nombre = this.txtNombreConsulta.getText();
            consultaProducto = controlP.consultar(nombre);
            
            
            // creo la tabla, los titulos
            tabla.addColumn("ID");
            tabla.addColumn("Nombre");
            tabla.addColumn("Cantidad");
            tabla.addColumn("Precio");
                 
            this.jTable1.setModel(tabla); //mi tabla toma el modelo
                 
            String[]dato = new String[4]; // un vector String con 4 posiciones
                 
            for(int i=0; i<consultaProducto.size(); i++){ // itera lista producto
                dato[0] =String.valueOf(consultaProducto.get(i).getId()); // estos datos vienen del get Producto
                dato[1] =consultaProducto.get(i).getNombre();
                dato[2] =String.valueOf(consultaProducto.get(i).getCantidad());
                dato[3] =String.valueOf(consultaProducto.get(i).getPrecio());
                     
                tabla.addRow(dato);// agrega una nueva fila a la tabla
            }
                 
            }
             catch (Exception error){
                 JOptionPane.showMessageDialog(null,"Error: " + error); 
            }
        
    }//GEN-LAST:event_buttonConsultarActionPerformed

    private void txtCantidadActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActualizarActionPerformed

    private void txtPrecioActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActualizarActionPerformed

    private void txtNombreActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActualizarActionPerformed

    private void buttonRefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRefrescarActionPerformed
        // TODO add your handling code here:
        this.listar();
    }//GEN-LAST:event_buttonRefrescarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int fila = this.jTable1.getSelectedRow(); //obtener el numero de la fila que estoy clickeando
        //carga los valores de la fila en las cajas de abajo de la tabla
        
        
        this.labelIDActualizar.setText(this.jTable1.getValueAt(fila, 0).toString());
        this.txtNombreActualizar.setText(this.jTable1.getValueAt(fila, 1).toString());
        this.txtCantidadActualizar.setText(this.jTable1.getValueAt(fila, 2).toString());
        this.txtPrecioActualizar.setText(this.jTable1.getValueAt(fila, 3).toString());
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaProducto().setVisible(true);
            }
        });
    }
    
    
         // metodo Listar
         public void listar(){
             try{
                 ControlProducto controlP = new ControlProducto(); //crea objeto de controlador
                 DefaultTableModel tabla = new DefaultTableModel(); //crea un objeto tipo tabla
                 ArrayList<Producto> listaProducto = new ArrayList<>(); // crea un array de productos
                 listaProducto = controlP.listar(); // ejecutar metodo listar y lo guarda en la lista
                 
                 // creo la tabla, los titulos
                 tabla.addColumn("ID");
                 tabla.addColumn("Nombre");
                 tabla.addColumn("Cantidad");
                 tabla.addColumn("Precio");
                 
                 this.jTable1.setModel(tabla); //mi tabla toma el modelo
                 
                 String[]dato = new String[4]; // un vector String con 4 posiciones
                 
                 for(int i=0; i<listaProducto.size(); i++){ // itera lista producto
                     dato[0] =String.valueOf(listaProducto.get(i).getId()); // estos datos vienen del get Producto
                     dato[1] =listaProducto.get(i).getNombre();
                     dato[2] =String.valueOf(listaProducto.get(i).getCantidad());
                     dato[3] =String.valueOf(listaProducto.get(i).getPrecio());
                     
                     tabla.addRow(dato);// agrega una nueva fila a la tabla
                 }
                 
             }
             catch (Exception error){
                 JOptionPane.showMessageDialog(null,"Error: " + error); 
             }
         }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonActualizar;
    private javax.swing.JButton buttonConsultar;
    private javax.swing.JButton buttonEliminar;
    private javax.swing.JButton buttonRefrescar;
    private javax.swing.JButton buttonRegistrar;
    private javax.swing.JComboBox<String> cboxCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelIDActualizar;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCantidadActualizar;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreActualizar;
    private javax.swing.JTextField txtNombreConsulta;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtPrecioActualizar;
    // End of variables declaration//GEN-END:variables
}
